fix starship config

diff --git a/home/.chezmoiscripts/run_once_install.sh.tmpl b/home/.chezmoiscripts/run_once_install.sh.tmpl
--- a/home/.chezmoiscripts/run_once_install.sh.tmpl
+++ b/home/.chezmoiscripts/run_once_install.sh.tmpl
@@ -9,18 +9,21 @@ sudo apt update
 sudo apt upgrade -y
 sudo apt autoremove -y
 
-# install all the things
+# # install all the things
 sudo apt install -y \
     fzf \
     bat \
     ripgrep \
     neofetch \
-    keychain
+    keychain \
+    || true # prevent missing packages from failing the script
 
 # generate ssh key
-ssh-keygen -t ed25519 -C "$email" -f "$HOME"/.ssh/id_ed25519 -q -P
+test -f "$HOME"/.ssh/id_ed25519 || ssh-keygen -t ed25519 -C "$email" -f "$HOME"/.ssh/id_ed25519 -q
 
 # install Starship shell
-curl -sS https://starship.rs/install.sh | sh
+curl -sS https://starship.rs/install.sh | sh -s -- -y
 
-sudo ln -s /bin/batcat /bin/bat
+if [ -f "/bin/batcat" ]; then
+    sudo ln -s /bin/batcat /bin/bat
+fi
